repos:

  - repo: local
    hooks:

      - id: flake8
        name: flake8
        entry: flake8 --count --color always
        language: system
        types: [python]
        require_serial: true

      - id: ruff
        name: ruff
        entry: ruff check --output-format concise
        language: system
        types: [python]
        require_serial: true

      - id: pylint
        name: pylint
        entry: pylint --output-format colorized
        language: system
        types: [python]
        require_serial: true

      - id: mypy
        name: mypy
        entry: mypy --sqlite-cache
        language: system
        types: [python]
        require_serial: true

      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]
        require_serial: true
