[tool.flake8]
max-line-length = 99

[tool.ruff]
target-version = "py312"
line-length = 99

[tool.ruff.lint]
select = ["ALL"]
ignore = [
	"Q000",		# using single quotes
	"I001",		# unsorted imports
	"D",		# missing docstrings

	"T",		# print pprint usage

	"S602",		# shell equals true
]

[tool.pylint.main]
jobs = 0

[tool.pylint.format]
max-line-length = 99

[tool.pylint."message control"]
disable = [
	"missing-docstring",
	"duplicate-code",
]

[tool.pyright]
analyzeUnannotatedFunctions = true

[tool.mypy]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = "googlesearch"
follow_untyped_imports = true

[[tool.mypy.overrides]]
module = "weasyprint"
follow_untyped_imports = true
