[tool.flake8]
max-line-length = 120
extend-ignore = [
	"F541",		# F541: f-string is missing placeholders
]

[tool.ruff]
target-version = "py312"
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = [
	"F541",		# f-string is missing placeholders
	"Q000",		# using single quotes
	"D",		# missing docstrings
	"ANN",		# missing type annotations

	"ERA001",	# commented code

	"I001",		# unsorted imports

	"T201",		# print found

	"S602",		# shell equals true
]

[tool.pylint.format]
max-line-length = 120

[tool.pylint."message control"]
disable = [
	"unspecified-encoding",
	"f-string-without-interpolation",
	"missing-docstring",
	"duplicate-code",
]

[tool.pyright]
analyzeUnannotatedFunctions = true

[tool.mypy]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = "googlesearch"
follow_untyped_imports = true

[[tool.mypy.overrides]]
module = "weasyprint"
follow_untyped_imports = true
